[theme]
theme = "native"
[theme.overrides]
separator = ""
idle_bg = "#333344"
idle_fg = "#ffffff"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "custom"
command = "acpi -b"
interval = 5

[[block]]
block = "custom"
command = "echo  $USER@$HOST"
interval = "once"
[[block.click]]
button = "left"
cmd = "wofi --show drun --allow-images"

[[block]]
block = "custom"
command = "echo  `pacman -Qsq | wc --lines`"
interval = 20

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'󰃭 %a %d/%m   %R') "
